#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BIN="$ROOT/.tools/contracts/bin"
"$ROOT/scripts/contracts/bootstrap-tools.sh"

rm -rf "$ROOT/tools/contracts/generated"
mkdir -p \
  "$ROOT/tools/contracts/generated/openapi-go" \
  "$ROOT/tools/contracts/generated/openapi-web" \
  "$ROOT/tools/contracts/generated/jsonschema" \
  "$ROOT/tools/contracts/generated/proto-go" \
  "$ROOT/tools/contracts/generated/proto-python"

{
  printf '// Code generated by oapi-codegen v2.8.0 from a non-serving foundation contract. DO NOT EDIT.\n'
  "$BIN/oapi-codegen" \
    -generate types \
    -package foundation \
    "$ROOT/tools/contracts/foundation/openapi.yaml"
} > "$ROOT/tools/contracts/generated/openapi-go/foundation.gen.go"

gofmt -w "$ROOT/tools/contracts/generated/openapi-go/foundation.gen.go"

(
  cd "$ROOT"
  pnpm exec orval --config tools/contracts/orval.foundation.config.ts
  pnpm exec json2ts \
    -i tools/contracts/foundation/schema.json \
    -o tools/contracts/generated/jsonschema/foundation.d.ts \
    --unknownAny=false
  node scripts/contracts/compile-jsonschema-validator.mjs
)

(
  cd "$ROOT/tools/contracts/foundation/proto"
  "$BIN/buf" dep update
  "$BIN/buf" generate --template buf.gen.yaml
)

# Production public REST artifacts are generated from the canonical OpenAPI authority.
"$ROOT/scripts/contracts/generate-public-rest.sh"
