-- BodySense vNext baseline rollback.
-- Extensions are intentionally retained because they may predate this application schema.
DROP TABLE IF EXISTS
    public.agent_interactions,
    public.agent_tool_calls,
    public.ai_output_reviews,
    public.assessment_reports,
    public.assessment_rollout_observations,
    public.body_state_evidence,
    public.body_state_facts,
    public.body_state_hypotheses,
    public.body_state_observations,
    public.body_state_revisions,
    public.body_states,
    public.consultation_rollout_observations,
    public.consultation_sessions,
    public.conversation_shares,
    public.conversations,
    public.diagnosis_analyses,
    public.diagnosis_analysis_freshness,
    public.diagnosis_candidate_assessments,
    public.diagnosis_candidates,
    public.diagnosis_rollout_observations,
    public.document_extraction_runs,
    public.document_indicator_reviews,
    public.interventions,
    public.job_events,
    public.jobs,
    public.knowledge_clips,
    public.knowledge_publication_observations,
    public.knowledge_publications,
    public.knowledge_segments,
    public.knowledge_sources,
    public.knowledge_units,
    public.messages,
    public.outcomes,
    public.privacy_erasure_requests,
    public.runs,
    public.runtime_events,
    public.thread_projection_messages,
    public.thread_projection_tool_calls,
    public.thread_projections,
    public.training_logs,
    public.training_plans,
    public.treatment_revisions,
    public.treatment_rollout_observations,
    public.treatments,
    public.user_profiles,
    public.user_uploads,
    public.users CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_at_column() CASCADE;
