// Code generated by scripts/body-region/generate-go-validator.mjs; DO NOT EDIT.
// Source of truth: apps/web/src/features/body-explorer/data/body-regions.v1.json

package service

var canonicalBodyRegionIDs = map[string]struct{}{
	"abdomen":         {},
	"ankle.left":      {},
	"ankle.right":     {},
	"calf.left":       {},
	"calf.right":      {},
	"chest":           {},
	"elbow.left":      {},
	"elbow.right":     {},
	"foot.left":       {},
	"foot.right":      {},
	"forearm.left":    {},
	"forearm.right":   {},
	"gluteal.left":    {},
	"gluteal.right":   {},
	"hand.left":       {},
	"hand.right":      {},
	"head":            {},
	"hip.left":        {},
	"hip.right":       {},
	"knee.left":       {},
	"knee.right":      {},
	"lower_back":      {},
	"neck":            {},
	"pelvis":          {},
	"scapular.left":   {},
	"scapular.right":  {},
	"shoulder.left":   {},
	"shoulder.right":  {},
	"thigh.left":      {},
	"thigh.right":     {},
	"upper_arm.left":  {},
	"upper_arm.right": {},
	"upper_back":      {},
	"wrist.left":      {},
	"wrist.right":     {},
}

// IsCanonicalBodyRegionID validates a durable BodyRegionId against the generated
// BodyRegionOntology v1 set. The JSON ontology remains the source of truth.
func IsCanonicalBodyRegionID(id string) bool {
	_, ok := canonicalBodyRegionIDs[id]
	return ok
}

// NewCanonicalBodyRegionIDValidator adapts the generated ontology set to the
// durable BodyState validation seam.
func NewCanonicalBodyRegionIDValidator() BodyRegionIDValidator {
	return BodyRegionIDValidatorFunc(IsCanonicalBodyRegionID)
}
